### ISSUE TITLE
Kubeflow stuck at creating new notebook servers

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/aaw-kubeflow-containers#368] opened 2022-07-11 18:45 UTC
**Description of Issue**

I’m having difficulty creating new notebook servers on https://kubeflow.aaw.cloud.statcan.ca/. Some users are reporting similar difficulty and though the specifics may vary the end result is we are unable to do our work.

**Observations**

- Some users cannot use k8scc01covidacr.azurecr.io/sas:latest but I can (sometimes). 
- Protected B seems to be an issue for some users but not me (but sometimes it is).
- Failure to create new notebook servers is inconsistent with respect to image type and Protected B status (but for some users it's always Protected B that causes the problem).

**Steps to Reproduce**

- Login to https://kubeflow.aaw.cloud.statcan.ca/
- In Notebooks, create a new server.
  -  Select an image: desktop, JupyterLab, custom...
  - Use default settings or enable/disable Protected B, MinIO...
  - Wait (the notebook server may or may not be created)
    - Sometimes after a few minutes the server will be created. Sometimes it will be stuck for days.

**Screenshot**

![image](https://user-images.githubusercontent.com/8212170/178348338-981353fc-eb78-4ab1-8461-aa39dc3194c8.png)

**Comment by vexingly** [comment] 2022-07-13 19:05
Was able to reproduce this again and pulled a few more logs, my pod created at 14:17 wasn't available until 14:29, which isn't the longest delay but is more than is expected (unless a new node is being added).

A lot of Pod creating events from kubeflow notebook controller and azure-npm, but then the pod is failing health checks after that, notebook controller can't find the notebook even though the pod is started successfully.

Pod events:
```sql
Readiness probe failed: Get "http://10.133.71.32:15021/healthz/ready": dial tcp 10.133.71.32:15021: connect: connection refused
juypaterlabby-0

Readiness probe failed: HTTP probe failed with statuscode: 500
juypaterlabby-0
```

notebook-controller-deployment-6879f4f9b6-ksgh7
k8scc01covidacr.azurecr.io/kubeflow/notebook-controller:0524491606c8c4477d9b2c887948a12d7660a3e4
```sql
2022-07-13T18:21:26.253Z ERROR controllers.Notebook unable to fetch Notebook {"notebook": "pat-ledgerwood/juypaterlabby-0.17017657499f9284", "error": "Notebook.kubeflow.org \"juypaterlabby-0.17017657499f9284\" not found"}
```

Complaints from kube-proxy, no endpoint for the pod would explain the failing healthcheck:
kube-proxy-sdsnq
```sql
I0713 18:21:27.253166 1 service_health.go:183] Not saving endpoints for unknown healthcheck "pat-ledgerwood/juypaterlabby"
```

Looks the statefulset reissues the pod a few times and at 14:29 it finally becomes available, from the azure-npm and kube-proxy point of view I see:
azure-npm-nx2hl
```sql
I0713 18:28:40.920257 1 podController.go:321] Successfully synced 'pat-ledgerwood/juypaterlabby-0'
Row: 342; Column: 4
```
kube-proxy-9bdqw
```sql
I0713 18:28:42.553058 1 endpointslicecache.go:354] Setting endpoints for "pat-ledgerwood/juypaterlabby:http-juypaterlabby" to [10.133.92.143:8888]
```

So possibly kube-proxy is not being told to set the end points before this point, azure-npm is getting backed up possibly?

**Comment by bryanpaget** [comment] 2022-07-18 13:07
Still having issues.

![image](https://user-images.githubusercontent.com/8212170/179517864-5f8e9c5e-aba8-46d7-8adb-a85364d62290.png)

**Comment by vexingly** [comment] 2022-07-25 11:47
Last week (July 21st) there was an istio update in prod which may have had an impact on this issue, please report if any change in its occurrence is noticed!

**Comment by chuckbelisle** [comment] 2023-06-14 13:48
Needs to be re-tested to confirm if issue is still occuring

**Comment by wg102** [comment] 2023-09-08 13:01
Tried booting three sas images, each booted in less than 2 minutes


![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/14837042/03a1dbb4-3974-4c81-83cb-f07a713bf5f1)

(Two images since the last one took like 20 seconds longer.

![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/14837042/2a429d74-2487-47bc-8c09-55148302a05c)

**Comment by wg102** [comment] 2023-09-08 13:13
Jup B 

![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/14837042/9b534b6e-d41f-4855-99d2-44c60b219e85)

Ubuntu B


![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/14837042/cee0698f-5a72-4f97-b1ae-a2fe0a44fc7d)

Sas b


![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/14837042/e37028d4-849f-43b3-8615-235bf870b00e)


Rstudio B:
This is the longest image by far for pulling, it took around 2 or 3 min  But the description seems normal


![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/14837042/3758217a-ec22-4d8d-b537-f87d956a0bbd)




![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/14837042/6ef92c2e-1d22-4c22-b67a-bacab60e0bcd)


Tried two more time 

![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/14837042/683009eb-2e66-4c3d-92f6-9d6c0fb7e6ee)



![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/14837042/26ba8454-1cd9-4bca-a933-77e25a11b391)



The action that seems to take the longest, when it does is


![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/14837042/699357c3-3697-462a-b3f7-2ab44fd0f922)

**Comment by wg102** [comment] 2023-09-08 13:15
I think this is no longer an issue, since none of the events mentioned higher in the issue happened, even the longest queries are not long because of such exceptions or errors. So unless a user or programmer reports this is happening again, I would consider the matter closed.

**Comment by wg102** [comment] 2023-09-08 13:32
Comment by @vexingly : Looks good, unless we onboard 100 new users I don't think we would be able to reproduce any of those types of issues!. 

I will therefore close the issue unless reported again.

**Closed by wg102** 2023-09-08 13:32 UTC
Labels: kind/bug, triage/needs-info, triage/support
