### ISSUE TITLE
Fix Failing builds 

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/aaw-kubeflow-containers#541] opened 2023-10-10 17:16 UTC
# EDIT
### Maybe just close this as Souheil is doing https://github.com/StatCan/aaw/issues/1855 ?

--------

See our recent nightly builds
https://github.com/StatCan/aaw-kubeflow-containers/actions/runs/6461703540

Copying over thread from Slack

```
Issue seems to be after that:
"@jupyterlab/server-proxy@2.1.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=4.0.6 <4.1.0          >=1.0.0 <2.0.0||>=2.0.0 <3.0.0||>=3.0.0 <4.0.0@jupyterlab/application
>=4.1.6 <4.2.0          >=1.0.0 <2.0.0||>=2.0.0 <3.0.0||>=3.0.0 <4.0.0@jupyterlab/apputils
>=4.0.6 <4.1.0          >=1.0.0 <2.0.0||>=2.0.0 <3.0.0||>=3.0.0 <4.0.0@jupyterlab/launcher


Pat Ledgerwood

We're forcing the version of the server-proxy to 2.1.2 so that is easy enough to change... but I'm confused why it broke now, the version of jupyterlab we're using didn't change

Pat Ledgerwood
Should not have changed anyways... maybe they just updated the dependency information or something


Pat Ledgerwood

Maybe we should just get rid of those extension installs based on the meesage (Deprecated) Installing extensions with the jupyter labextension install command is now deprecated and will be removed in a future major version of JupyterLab.


Jose Matsuda
yeah unless we just address it directly


Pat Ledgerwood
Seems like they are not even installed properly anyway, if I look at the extensions in prod jupyter-server-proxy 4.0.0 extension is installed already and plotly is also a newer version than listed
```

**Comment by chuckbelisle** [comment] 2023-10-18 13:37
Closing tasks as it became duplicate of work done in 1855 (linked above)

**Closed by chuckbelisle** 2023-10-18 13:37 UTC
Labels: triage/support
