### ISSUE TITLE
BI and Graphics

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/aaw-kubeflow-containers#314] opened 2022-01-24 21:52 UTC
## BI

Not sure what BI options have been explored but from my experience at Health Canada I'd say that should be a priority. People like the easiness of Power BI and I can't blame them, it saves time over R Shiny for basic stuff.

Some options I've found:

- [RAW Graphs](https://github.com/rawgraphs/rawgraphs-app), check out their [homepage](https://rawgraphs.io/) to see how it looks.
- [Redash](https://github.com/getredash/redash): connect to any data source, easily visualize, dashboard and share your data.
- [Metabase](https://github.com/metabase/metabase): very simple.
- [Apache Superset](https://github.com/apache/superset): looks advanced.
- [Seal Report](https://github.com/ariacom/Seal-Report): it's written in C#.

### Outdated

- [Jupyter Dash](https://github.com/plotly/jupyter-dash) hasn't been updated in a year!

## Graphics

Additionally, would some UI tools for dashboard, website and user interface mockups be useful? 

- [Penpot](https://github.com/penpot/penpot).

**Comment by bryanpaget** [comment] 2022-01-26 17:33
Should be part of a larger discussion on user needs with respect to BI and data visualization/communication.

**Comment by brendangadd** [comment] 2022-03-13 06:03
Duplicate of StatCan/daaas#478

**Closed by brendangadd** 2022-03-13 06:03 UTC
Labels: help-wanted, area/engineering, priority/longterm, kind/feature, kind/design, size/XL, area/ux
